### ISSUE TITLE
Continuous Integration checks (travis/gitlab-CI/drone/...)

### ISSUE THREAD

**Issue by n8225** [awesome-selfhosted/awesome-selfhosted#1852]
@nodiscc Checks need to be set up after move to org.  Do we want to stick with Travis, move to github actions, or one of the other CI/CD providers.  I've been using github actions on the static site https://github.com/n8225/awesome-selfhosted-gen/actions.  https://n8225.github.io/awesome-selfhosted-gen/ now updates daily.

**Comment by evaryont** [comment]
We may want to consider an alternative if we want to seriously consider self-hosting this project as well. (See https://github.com/awesome-selfhosted/awesome-selfhosted/issues/89#issuecomment-526728253 and surrounding comments for that conversation.) Though, the best-in-class self-hosted CI is Gitlab's IMO but that's a hefty lift considering it doesn't integrate with anything other than Gitlab.

**Comment by SuperSandro2000** [comment]
Drone + Gitea?

**Comment by nodiscc** [comment]
> stick with Travis

We already have a travis config so it makes sense to go with this for the time being. I will set it up this weekend.

> move to github actions

Tying our work with proprietary, non self-hostable software even more is not the way to go IMHO. I understand it's convenient.

> best-in-class self-hosted CI is Gitlab's IMO but that's a hefty lift considering it doesn't integrate with anything other than Gitlab

True. I have been using it for some time (both SaaS and self-hosted) and it works great and is slowly becoming industry standard. I will set it up for our current [mirror](https://gitlab.com/awesome-selfhosted/awesome-selfhosted) and the repo can contain both `.travis.yml` and `.gitlab-ci.yml` without problems. We'll see if it's possible to integrate with our Github repo somehow.

> Drone + Gitea?

I have a personal Gitea instance but did not have time to set up drone yet. @SuperSandro2000 if you have a (public) drone instance we can interact with this would be a great addition, and it gives us another option.

Any suggestions are welcome.

**Comment by SuperSandro2000** [comment]
> I have a personal Gitea instance but did not have time to set up drone yet. @SuperSandro2000 if you have a (public) drone instance we can interact with this would be a great addition, and it gives us another option.

no, it was on my todo to try out later but I didn't get to it yet and wouldn#t count on it. Way to much other stuff to do currently.

**Comment by nodiscc** [comment]
I have restored Travis checks as they were before, and updated all URLs to reflect the change of ownership (https://github.com/awesome-selfhosted/awesome-selfhosted/commit/2c6e7ab9d2b6c4b44a6bb8f6b2a6a4371950a1c0).

Let's keep this issue open to keep track of work on other CI systems.

**Comment by SuperSandro2000** [comment]
You could have made some of those links relative.

**Comment by nodiscc** [comment]
From https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2266#issuecomment-751400333:

> We also need to change our CI provider (travis CI) who will soon start enforcing severe job time limits for free projects (let's move that topic to #1852). Similar problem mentioned at shaarli/Shaarli#1649 in which we evaluated other CI systems (Gitlab CI, Drone, GH actions...). Not an excuse for not optimizing our checks runtime/bandwidth consumption :)

**Comment by nodiscc** [comment]
https://travis-ci.org/github/awesome-selfhosted/awesome-selfhosted/builds
> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

**Comment by nodiscc** [comment]
I will be moving awesome-selfhosted's CI pipeline to [Github Actions](https://github.com/awesome-selfhosted/awesome-selfhosted/actions/) soon (it is not self-hosted but Travis was not either). The only satisfying FOSS CI service I have worked so far is Gitlab CI (I have been running into instablilities with Drone, have not tried many others, check https://github.com/ligurio/awesome-ci). We can setup Gitlab<->Github<->other integrations later if needed, but for now let's just move to GH Actions and cleanup/improve the tooling a bit.

**Comment by n8225** [comment]
I've got a little free time today I'll see if I can get started on this.

**Comment by nodiscc** [comment]
https://github.com/nodiscc/hecat will handle URL checks, and enreiching the list with automatically gathered data, as part of https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038.

Our CI pipeline should run on GH actions and rely on `hecat` and https://github.com/awesome-selfhosted/awesome-selfhosted-data as much as possible. In fact there is no point in having a CI pipeline on https://github.com/awesome-selfhosted/awesome-selfhosted itself since this will just be an automatically generated file/repository.

**Comment by nodiscc** [comment]
Blocked by https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038

**Comment by nodiscc** [comment]
Fixed in https://github.com/awesome-selfhosted/awesome-selfhosted-data/actions/workflows/update-metadata.yml.

Currently, data from https://github.com/awesome-selfhosted/awesome-selfhosted must be synced manually to https://github.com/awesome-selfhosted/awesome-selfhosted-data (`make import update_metadata`) which I do from time to time, but when https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038 is completed and synchronization happens the other way around automatically, then there will be no remaining manual steps at all (except actually curating the list, see https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3558).

Anyway, closing since the current automation level is acceptable, and will only get better over time. Feel free to report separate issues for anything else.
