### ISSUE TITLE
Creating releases?

### ISSUE THREAD

**Issue by blacs30** [awesome-selfhosted/awesome-selfhosted#2235]
I think it would be great to have releases, e.g. once a month or quarter which contains a changelog of added, changed and deleted software from the list.

That would make release watch possible and gives good overview of changes.

**Comment by spekulatius** [comment]
Yeah, I thought about this too - it would make it much easier to keep updated but without getting all the notifications for every new project

**Comment by nodiscc** [comment]
I thought about this a while ago, I agree.  But it needs to be automated somehow, no way I'm redacting changelogs by hand. So probably related to https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038

**Comment by theowenyoung** [comment]
I didn't notice this issue before, but the issue is exactly my issue before, that's why I created trackawesomelist.com. And of course created a profile: https://www.trackawesomelist.com/awesome-selfhosted/awesome-selfhosted/  for awesome-selfhosted.

I created a workflow automatically to parse awesome-selfhosted's readme, and getting every items' commit time, then generate a static html page for it.

With this link, we can read the latest updates of awesome-selfhosted by day/week, free, daily updated. I hope this can help you.

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this issue worked on, please check contribution guidelines there, and open a new PR/issue.
