### ISSUE TITLE
Check out VivumLab

### ISSUE THREAD

**Issue by denis-ev** [awesome-selfhosted/awesome-selfhosted#2353]
https://github.com/VivumLab/VivumLab

**Comment by 4oo4** [comment]
Thanks for sharing, this looks cool. Just curious of how this differs from Yunohost and what advantages it has? I'm getting 404s when trying to read your docs.

Cheers

**Comment by denis-ev** [comment]
Yeah, we just changed the docs service. 
The right link is https://vivumlab.com and docs moved to https://vivumlab.com/docs  
There is a big PR almost ready to be merged. 
With some fixes including the links too.

**Comment by voryzen** [comment]
@4oo4 
Thanks for trying to check us out. @denis-ev is correct, we are not far away from pushing a major change to make Vivum more accessable for others.. The docs should be ready by release time

To answer your question, VivumLab (will) only require docker on the host PC, and deploys various services to a remote server with the use of docker containers; you don't need to install a complete OS that you may (or may not) already be familiar with, to use VivumLab.
Just download the project, it pulls the docker container, drops you into a shell and you're good to go. We support deploying to CentOS, Debian, and Ubuntu, and (will be) available for users in english, spanish, german, and french.

VivumLab is CLi based at the moment, and because we (the developers) are users of our own software and try to be very present in our community, we focus on ease of use. There has been talk of a GUI, but in true open source fashion, we want to be good at the CLi thing first.

VivumLab is still growing, but we boast a good core team of multinational developers; with very high aspirations for VivumLab, we are shooting for the stars!
