### ISSUE TITLE
Questions about deprecation of awesome-sysadmin

### ISSUE THREAD

**Issue by vaidd4** [awesome-selfhosted/awesome-selfhosted#2482]
Since November 2020 the repo [n1trux/awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) as been deprecated in favour of [this forum](https://awesome.tilde.fun/t/sysadmin).

As it is probably not up-to-date, is it a good idea to still redirect to this repo ? Should we use another fork ? Should we redirect to the forum instead ?

(I made this issue to open a discussion.)

**Comment by koalp** [comment]
I don't understand why using a forum would be better. I think makes it harder to search as you can't ctrl-f the whole list. 
*It's something I often do when I want to look for an alternative for a specific software : I directly search for a software I know rather than a category*

Therefor, I think it would be better to use another fork or another markdown file

**Comment by UnixNight** [comment]
Funny enough, I noticed the deprecation of the repo and made a [pull request](https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2483) to change the link. While the forum might be a little hard to search with a ctrl+f, I think it would be better to link to it as it's the currently active list. They have a search function in there and they also link back to the old repo as a sticky post so it's not like they're hiding the old list

**Comment by nodiscc** [comment]
>  don't understand why using a forum would be better. I think that it makes it harder to search

I discussed these concerns and a few others with @n1trux when awesome-sysadmin was moved to a forum https://github.com/sindresorhus/awesome/pull/1904. Some time has passed and with a bit of hindsight I think the forum is not as good as the markdown-based list:
- no Ctrl+F search, impossible to list all entries at once
- impossible/hard to automate maintenance/curation tasks/checks (https://travis-ci.org/github/awesome-selfhosted/awesome-selfhosted/builds)
- impossible/hard to replicate/fork the list in an easy way, not portable (you need to setup a flarum instance and find a way to copy the data)
- the main point was to make the contribution/maintenance process simpler (pull requests/markdown formatting is kind of a high barrier to entry), but it actually makes it harder (you need to send your proposed changes in a forum post, then the admin has to merge it manually to the main list. The forum posts/replies themselves are not curated - in this regard it's not different from requesting an addition in https://github.com/awesome-selfhosted/awesome-selfhosted/issues?q=is%3Aissue+is%3Aopen+label%3Aaddition)
- doesn't solve the one-entry-fits-multiple-categories problem
- the number of contributions has dropped significantly (may be a good or a bad thing depending on how you want to manage the project)
- ...

There is a positive change though (it's self-hosted ;) )

We can come back to that later. The important point right now is that we can't link to the old, unmaintained list anymore. 

Possible solutions:

**1.** Link to the forum instead (proposed in https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2483)

For the reasons I listed above I don't think it's satisfying. It makes contributions harder, contributors now have to search through the forum to find possible duplicates. Finding something is also harder (I used to visit awesome-sysadmin once in a while, since the forum move I think I've visited it twice, and gave up after a few minutes)

---------------------

**2.** Fork the original list under https://github.com/awesome-selfhosted/awesome-sysadmin

I'm not going to maintain a separate list, and manpower to do it is lacking right now. Unless someone want to pick up this task but this is no small task, and it has to hold to the same quality standards it used to.

-------------------

**3.** Hardest solution in the short term, best in the long term: what I described in https://github.com/sindresorhus/awesome/pull/1904: move all data from awesome-selfhosted/sysadmin to a machine-readable format (YAML/JSON...) (https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038) + write a tool to generate a static website + markdown version of the lists (with customizable filters - only include software matching `tag: selfhosted` or `tags: sysadmin`, depending on the target)

- https://github.com/n8225/awesome-selfhosted-gen gets the basics but there are [issues](https://github.com/n8225/awesome-selfhosted-gen/issues), it will need to be adapted for general-purpose software list generation, a fully custom Go implementation might also not be the best choice
- I have a prototype of general-purpose software list generator using YAML as a storage backend, with minimalist parsing/filtering logic, and static site rendering using standard components (Sphinx). I will clean it a bit and release a development version. Might take some time. Basically a minimal, FOSS [AlternativeTo](https://alternativeto.net/)-like

This would make maintenance, contribution and automation so much easier, we can leverage YAML storage to store information that we can't manage right now using plain markdown, enable tag-based categories, show more metadata, allow search/filtering, enable re-use of data, etc.

------------------

**4.** Undo the move we did a [way back](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls?page=35&q=is%3Apr+awesome-sysadmin+is%3Aclosed), take back all relevant sections into awesome-selfhosted (basically everything that reads `See https://github.com/n1trux/awesome-sysadmin...` here)

- In last resort I am ok with this. The point of the original merge was to avoid duplication of effort, but the forum doesn't do the job anymore for me (and apparently other people).
- It will clobber the list (what we were trying to avoid originally), but it can be done easily, quickly, and we can always reuse the data if **3.** is implemented someday

----------

If you see other possible solutions or have something to add, please do. Otherwise I'll try to get 4. done by May

**Comment by n1trux** [comment]
I'd be fine to move my repository to the awesome-selfhosted organisation under two small conditions:

*  I get maintainer access and/**or** a small notice that I maintained the list from date x to y (don't remember).
* we **think very hard** about moving all these glorified textfiles off github into a proper web application with discussion features.
  * like alternativeto.net, but FOSS.

This proposal is a mix of @nodiscc's [solutions](https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2482#issuecomment-817224208) 2, 3 and 4.

**Comment by vaidd4** [comment]
Using github pages with a forum like discourse (or other offering free hosting for opensource), would be a viable solution?
It would solve the hosting question at least.

**Comment by nodiscc** [comment]
hi, sorry for the delay

> I get maintainer access and/or a small notice that I maintained the list

sure. We should also build an [AUTHORS.md](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/AUTHORS.md) or similar listing all contributors ensuring proper copyleft/CC-BY-SA-4.0 compliance.

> moving all these glorified textfiles off github into a proper web application

Yes, this is the first thing to do. Check https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038, the plan is to
- move the data to a human **and** machine-readable format like YAML
- keep using git for storage and change management/contributions
- create a custom script and let CI/CD generate a static, multi-page site with better sorting/categorization/tagging/layout...
- this ensures portability (the static output is easy to host on readthedocs or other static site SaaS hosts, or a simple web server, data can be mirrored with a simple `git clone`. Anyone can rebuild the site on their own box. The basic YAML template for a project projects can be edited/copy-pasted around easily).
- It should also output legacy markdown to keep https://github.com/awesome-selfhosted/awesome-selfhosted up-to-date (although it's absolutely not the best way to view the list, I think its good to have a centralization point for contributions, if at some point we move it off Github it will happen _gradually_ and _carefully_)
- It does not reinvent the wheel too much (my basic ugly generator prototype is ~300 line python, and it generates intermediary markdown pages, which are then converted to HTML by `sphinx`. I will publish it ASAP. It still needs the bells and whistles like metadata retrieval, etc, but the basics are there). 

> with discussion features

I don't want to moderate a forum/astroturfing contest, and I think it is best to keep things separate, so the best solution is to link to a designated forum thread for each section, and a reviews thread for each entry (if there is a brave soul to host a maintain a forum). There is a lot of activity on reddit/r/selfhosted but it does not lend itself well to this kind of organization.

**Comment by n1trux** [comment]
Okay then, I'm fine with that :)

Can I move the existing repo into your org or would you create a new repo? If the latter, how should I move people to the new repo? I think somewhere in Github you could set a redirect, but I can't find where that was.

**Comment by Kickball** [comment]
@n1trux I had the same concerns when kickball/awesome-selfhosted was transfered to awesome-selfhosted/awesome-selfhosted, but transfering the project (rather than re-creating) worked well as GitHub adds an automatic redirect to the new project.

Their announcement is here: https://github.blog/2013-05-16-repository-redirects-are-here/

You can see the redirect still live at: https://github.com/kickball/awesome-selfhosted

**Comment by n1trux** [comment]
Thanks @Kickball, tried moving but got:

>  You don’t have the permission to create public repositories on awesome-selfhosted

@nodiscc, I'd need rights for awesome-selfhosted to be able to create repositories there (nothing more), as the transfer doesn't work otherwise and apparently entering you as collaborator doesn't give you enough rights to transfer the repo.

**Comment by nodiscc** [comment]
@n1trux added you to the organization (https://github.com/orgs/awesome-selfhosted/people/pending_invitations). You should be able to transfer the repo now (?)

Also created a new `Team` (https://github.com/orgs/awesome-selfhosted/new-team -> `awesome-syadmin`) within the org so you can keep admin privileges on `awesome-selfhosted/awesome-sysadmin`. Let me know if things are not working right.

**Comment by nodiscc** [comment]
Edit: just saw your edit. Cancelling changes on awesome-slefhosted org, unarchiving https://github.com/awesome-foss/awesome-sysadmin. Thanks!

Now we need to update our links https://github.com/n1trux/awesome-sysadmin -> https://github.com/awesome-foss/awesome-sysadmin

**Comment by nodiscc** [comment]
Re-enabled https://github.com/awesome-foss/awesome-sysadmin/issues

**Comment by Kickball** [comment]
@n1trux thanks for the invite. It seems to have expired, would you be able to resend it when you get chance please?

**Comment by n1trux** [comment]
> @n1trux thanks for the invite. It seems to have expired, would you be able to resend it when you get chance please?

Oh, only **just** saw your message. I really don't have a lot of time the last 3y, sorry :/

Invited you again as Owner.

**Comment by Kickball** [comment]
Thanks! I’ve accepted it this time 😊

**Comment by Epy** [comment]
Hello
Some questions: Could we move the README.md of awesome-sysadmin to a sysadmin-README.md (even in a temporary directory) in **this** repository, to improve its visibility and add missing informations (like langage and license) with PR.

Then it will be interesting to choose if both can be merged or if they should stay as multiple docs like other categories to limit the list's lenght.

Another question: I had a look on a static html generator using the yaml data, as you said here, but I saw that was already in progress. Do you need help ? I think it's a great idea to have this page, filter results from a search field or from tags..

**Comment by KieranRobson** [comment]
So with sysadmin having merges now, what is the road for this discussion? Are we moving things from sysadmin to self-hosted or are we leaving items at sysadmin and only transferring some sections over?

https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3167#discussion_r942491249 this suggests we are not moving things over while https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3166 suggests things are moving over 😆 

I have only been contributing for a couple months but happy to help where I can and am happy to take on more responsibility within these projects, , both with sysadmin and self-hosted, alongside any other related lists there are.

**Comment by nodiscc** [comment]
> https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3167#discussion_r942491249 this suggests we are not moving things over while https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3166 suggests things are moving over

We are moving `Status/Uptime pages` back to awesome-selfhosted, but `Monitoring` stays on awesome-sysadmin as it is more generic.

> am happy to take on more responsibility within these projects, , both with sysadmin and self-hosted

awesome-sysadmin will need new maintainers in the absence of @n1trux, let's finish https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038, https://github.com/awesome-selfhosted/awesome-selfhosted-data/milestone/1 first and move awesome-sysadmin to the new storage format/automation.

**Comment by nodiscc** [comment]
Feedback needed about possible quality guidelines for awesome-sysadmin: https://github.com/awesome-foss/awesome-sysadmin/pull/357

**Comment by WebSnke** [comment]
> Since November 2020 the repo [n1trux/awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) as been deprecated in favour of [this forum](https://awesome.tilde.fun/t/sysadmin).
> 
> As it is probably not up-to-date, is it a good idea to still redirect to this repo ? Should we use another fork ? Should we redirect to the forum instead ?
> 
> (I made this issue to open a discussion.)

@nodiscc
["this forum"](https://awesome.tilde.fun/t/sysadmin) is not even accessible anymore (unless it's just because of maintenance). This issue should therefore be closed.

**Comment by Epy** [comment]
The forum is unavailable since a long time, it's not maintenance ;)

**Comment by nodiscc** [comment]
- https://github.com/awesome-foss/awesome-sysadmin
- https://github.com/awesome-foss/awesome-sysadmin/issues/405
- https://github.com/awesome-foss/awesome-sysadmin/issues/416
