### ISSUE TITLE
Table with more information

### ISSUE THREAD

**Issue by RashadBrowne** [awesome-selfhosted/awesome-selfhosted#3175]
As suggested here
https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2534

and here

https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1118

a table formatted list with columns such as "ease of use", something to do with frequent updates to help weed out dead projects, features heck even the design since thats becoming more important as of late.

A table would just make it easier for viewers to pick a self hosted solution that suites them. As good as it would be for everyone to test out every solution and give proper feedback, some people barely even have the time to experiment with one solution much less 10 or 20 in some cases.

**Comment by RashadBrowne** [comment]
| Name | Description | Functionality(10) | Ease of Use(10) | Source Code |
| ------ | ------ | ------ | ------ | ------ |
| [Groceri.es](https://groceri.es/) | Web-based application to manage your recipes and plan your meals ahead. groceri.es keeps track of your menu plans and generates a groceries list for you.  | 8 |6|([Source Code](https://github.com/juriansluiman/groceri.es)) `MIT` `Python` |
| [kcal](http://demo.kcal.cooking/) | Track nutritional information about foods and recipes, set goals, and record a food journal to help along the way. Kcal is a personal system that focuses on direct control of inputs and a minimal, easy to use recipe presentation for preparing meals.|5 |9| ([Source Code](https://github.com/kcal-app/kcal))([Demo](http://demo.kcal.cooking/login)) `MPL-2.0` `PHP`|
| [Mealie](https://hay-kot.github.io/mealie/) | Material design inspired recipe manager with category and tag management, shopping-lists, meal-planner, and site customizations. Mealie is focused on simple user interactions to keep the whole family using the app. |7 |9|([Source Code](https://github.com/hay-kot/mealie)) `MIT` `Python`|
| [RecipeSage](https://recipesage.com) | A recipe keeper, meal plan organizer, and shopping list manager that can import recipes directly from any URL.|5 |8| ([Source Code](https://github.com/julianpoy/recipesage)) `AGPL-3.0` `Nodejs`|
| [Tandoor Recipes](https://docs.tandoor.dev/) | Django application to manage, tag and search recipes using either built-in models or external storage providers hosting PDFs, Images or other files.|8 |8|  ([Source Code](https://github.com/vabene1111/recipes/)),([Demo](https://app.tandoor.dev/)) `MIT` `Python`|

**Comment by nodiscc** [comment]
> Functionality(10)
> Ease of Use(10)

This is not something quantifiable, and also highly subjective. I would put 10/10 on every software/script I write. 

All "ratings" are going to depend heavily on what you intend to use the software for. We won't do case studies on behalf of readers of the list, because there are simply too many possible use cases - readers are expected to conduct their own evaluations of the software, like you did above, taking their own requirements into account. This should be done every time new software is added to one's tools and processes anyway.

This list also aims to be somewhat impartial (there are no "quality" requirements to be part of the list, except basic things like being maintained, being decently responsive for security issues, being Free/Open-source, having installation/setup instructions) so we definitely won't maintain ratings here.

Once https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038 is completed (soon), we will be able to add useful metrics to the list (number of stars, last update date, screenshots...), which could help users choosing the right software for their requirements.

Attaching a link to a review thread (on a site we won't maintain) to each item was discussed in https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1766, see comments there.

Closing

**Comment by RashadBrowne** [comment]
Understood, it would be far better for these ratings to be community driven but that would further complicate things.
