### ISSUE TITLE
Label software using a "Freemium" model as such

### ISSUE THREAD

**Issue by pharindoko** [awesome-selfhosted/awesome-selfhosted#3480]
It would be nice to see which of these self-hosted solutions have a paywall implemented
or to state it in the opposite direction => are completely free.

Nowadays there is a new business model by restricting access to important features that should be available out of the box for open source projects...

For example:
- Some tools restrict access to secure modern authentication using OpenIDConnect / Oauth or SAML.
- Some tools restrict access to a roles based or group base authorization model.

**Comment by KieranRobson** [comment]
All tools in the readme should be completely free, any tools with a pay wall should be in nonfree.md

If you find tools that aren't in the correct place, feel free to open a pr or issue to get them moved!

**Comment by nodiscc** [comment]
I think @pharindoko is referring to the fact that some of the completely Free software solutions have a "freemium" model or distinct Community (Free) and Professional (non-Free) editions. In some cases rather benign because the Free edition is fully functional, in some cases, restrictions are more severe (SSO and role-based access features are usually the first to suffer). In some cases the "Pro" features have never been part of the Community edition to begin with, in some cases they are removed from the Community edition as part of a new release (which is arguably worse).

So slapping a `⚠ Paywall` indiscriminately on all software that follows this model would not be very helpful, and a bit unfair. I have moved away from some solutions where that model was problematic, and happily use some others which are good in their Free edition, despite following that model.

There is usually a comparison page where prospective users/admins of these services can read about differences between different editions and decide by themselves. Even the [F-Droid anti-features page](https://f-droid.org/en/docs/Anti-Features/) does not cover this case (it was the inspiration for the [anti-features list here](https://github.com/awesome-selfhosted/awesome-selfhosted#anti-features)).

So unless a good case can be made, I don't think we should add such a label/anti-feature. It would fall under more general "quality" considerations which we won't consider here [[1]](https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3175).

**Comment by pharindoko** [comment]
@nodiscc 
thanks for your explanation.
I could imagine that this fits to "Non-Free Dependencies" mentioned in F-Droid anti-features page.

I think to label something as "paywall" would be wrong. It´s negative and it`s hard to separate what it meant by this.

But it would be helpful to label software as "free" that is free to self-host and does not restrict obvious fundamental things like Authentication (OIDC/Oauth) and Authorization (Groups) that make it unuseable in a production without paying for it.

**Comment by nodiscc** [comment]
>  could imagine that this fits to "Non-Free Dependencies" mentioned in F-Droid anti-features page.

It does not:

>> https://f-droid.org/en/docs/Anti-Features/#NonFreeDep
>> This Anti-Feature is applied to apps that require things that are not Free Software in order to run.
>> This does not mean that proprietary software is included in the app, but for example, it may depend on other software already being installed on your device. A common example would be an app that doesn’t run, or is not useful, unless you have Google Maps installed.

> does not restrict obvious fundamental things like Authentication (OIDC/Oauth) and Authorization (Groups) that make it unuseable in a production

These are only fundamental to your specific use case, many projects listed here does not provide SSO/OAuth/RBAC at all, yet they are still listed. Other people may consider other features as "essential" for their workflow, and then we would have to label all software that uses the "multiple editions" model as `Paywall/Freemium`. These programs are functional in their "Community"/Free editions, which is all that matters.

More importantly, since all software listed on awesome-selfhosted is Free and Open-Source, it can be forked to add the necessary features. If the upstream project does not accept patches to add "missing" functionality, a hard fork is always possible and would be accepted in the list.

There are limits to this rule, for example if the software arbitrarily locks itself after a certain amount of data/users/... is reached, and/or nags users about switching to the non-free/paid edition, this could arguably be removed from the list since it somehow contradicts _Freedom 0: The freedom to use the program for any purpose._

These considerations could belong to review threads/comparison/forums posts which we will not maintain here [[1]](https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1766) [[2]](https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1684) [[3]](https://github.com/awesome-selfhosted/awesome-selfhosted/issues/894)

Finally, it's up to the prospective admin/user to determine if the software is adapted to their use case, and the differences between editions is usually clearly outlined on the project's website (example [[1]](https://www.rocket.chat/pricing) [[2]](https://about.gitlab.com/pricing/feature-comparison/)...).

Closing but feel free to add additional information. Thanks

**Comment by pharindoko** [comment]
@nodiscc
Thanks for your discussion.

I guess I know now what I meant ... it`s called **open-core** model ...
https://en.wikipedia.org/wiki/Open-core_model

**Comment by nodiscc** [comment]
See also https://sso.tax/ -  A list of vendors that treat single sign-on as a luxury feature, not a core security requirement.
