### ISSUE TITLE
I'd like to add baby activity tracking app, though I'm unsure which category is the best

### ISSUE THREAD

**Issue by RikudouSage** [awesome-selfhosted/awesome-selfhosted#4043]
I want to add the project I'm working on, Baby Journal, an app for activity tracking (like feeding, diapers, sleeping etc.). Huge part of it is time tracking, so it might fit in that category, though I'm not sure. Can you provide help?

**Comment by nodiscc** [comment]
Related https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2073

It could be inserted into `Miscellaneous` first, then regrouped with other these other projects in a new `Health and Medicine` section.

Howver, [contributing guidelines](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/PULL_REQUEST_TEMPLATE.md) state:

>  Any software project you are adding was first released more than 4 months ago.

And the repositories at https://github.com/RikudouSage?tab=repositories&q=babyjournal&type=&language=&sort= do not fit this criteria. So I will close this for now. Feel free to submit your project when a stable release is made and is at least 4 months old.

**Comment by RikudouSage** [comment]
Why are you open source maintainers always so uninviting? Guess I don't need my project here.

**Comment by nodiscc** [comment]
You are very much welcome to submit your project, however it must adhere to the guidelines which are the same for all contributors (~1200 people so far), in order to keep the list high-quality. If you're interested in the discussion that led to this particular rule being added, you can find it here: https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3880

I'm sorry if my answer felt "uninviting", that was not my intention.
